stages:
- name: build
  type: docker-build
- name: push
  type: docker-push
  # repo may not contain tags
  repo: j18e/kubeline
  tags:
  - latest
  - $BRANCH-$KUBELINE_ITERATION
  - $KUBELINE_COMMIT_SHA_SHORT
