pipelines:
  kubeline:
    git_url: git@github.com:j18e/kubeline.git
    docker_secret: kubeline-docker-j18e
  public-ssh:
    git_url: git@github.com:j18e/ci-test-1.git
    docker_secret: kubeline-docker-j18e
  ifailcheck:
    git_url: https://github.com/j18e/ci-test-wejfiowejf1.git
    docker_secret: kubeline-docker-j18e
  ifailconfig:
    git_url: https://github.com/j18e/ci-test-2.git
    docker_secret: kubeline-docker-j18e
  ifail:
    git_url: https://github.com/j18e/ci-test-3.git
    docker_secret: kubeline-docker-j18e
    ##
    ## if git_branch is not specified, master is assumed
    ##
    # git_branch: master
#
# all other configuration in target repo /kubeline.yml
#
