git_key_secret_name: kubeline-git-key
git_key_secret_key: id_rsa
influxdb_host: influxdb
influxdb_db: kubeline
repos_dir: tmp/repos

repos:
- name: kubeline
  git_url: git@github.com:j18e/kubeline.git
  docker_secret: docker-j18e
- name: public-ssh
  git_url: git@github.com:j18e/ci-test-1.git
  docker_secret: docker-j18e
- name: ifailcheck
  git_url: https://github.com/j18e/ci-test-wejfiowejf1.git
  docker_secret: docker-j18e
- name: ifailconfig
  git_url: https://github.com/j18e/ci-test-2.git
  docker_secret: docker-j18e
- name: ifail
  git_url: https://github.com/j18e/ci-test-3.git
  docker_secret: docker-j18e
- name: ipass
  git_url: https://github.com/j18e/ci-test-1.git
  docker_secret: docker-j18e
    ##
    ## if git_branch is not specified, master is assumed
    ##
    # git_branch: master
#
# all other configuration in target repo /kubeline.yml
#
