version: '3'
services:
  kubeline:
    build: ../
    command:
    command:
    - --check-frequency=15
    - --namespace=kubeline
    - --influxdb-host=influxdb
    - --influxdb-db=kubeline
    - --config-file=/config.yml
    - --job-runner-image=j18e/job-runner:0.1.6
    volumes:
    - ./config.yml:/config.yml:ro
    - ~/.kube/config:/root/.kube/config:ro
    - ../templates:/work/templates:ro
    ports:
    - 8080:8080
