version: '3'
services:
  kubeline:
    build: ../
    command: dev -f /config.yml -s ./tmp/state.yml
    volumes:
    - ./config.yml:/config.yml:ro
    - ../tmp:/work/tmp
    - ~/.kube/config:/root/.kube/config:ro
    - ~/.ssh:/root/.ssh:ro
    ports:
    - 8080:8080
