version: '3'
services:
  job-runner:
    build: ../
    depends_on: ["influxdb"]
    command:
    - testline
    - --stages=1-build,2-push
    - --start=STARTED
    - --success=WON
    - --failure=LOST
    - --influxdb-host=influxdb
    - --influxdb-db=kubeline
    - --time-limit=3600
    - --log-dir=/logs
    volumes:
    - logs:/logs
  influxdb:
    image: "influxdb:1.5"
    environment:
      INFLUXDB_DB: kubeline
    ports:
    - 8086:8086
  grafana:
    image: "grafana/grafana"
    depends_on: ["influxdb"]
    environment:
      GF_SECURITY_ADMIN_PASSWORD: admin1
    ports:
    - "3000:3000"
    volumes:
    - "./datasource.yml:/etc/grafana/provisioning/datasources/datasources.yml:ro"
    - "./dashboard.yml:/etc/grafana/provisioning/dashboards/dashboards.yml:ro"
    - "./dashboard.json:/etc/grafana/dashboards/dashboard.json:ro"
volumes:
  logs:

