{%- set short_commit = commit[:6] %}
{%- set work_dir = '/kubeline-work' %}
{%- set log_dir = '/kubeline-logs' %}
{%- set env_vars_file = 'kubeline-vars.sh' %}
{%- set env_vars_path = log_dir + '/' + env_vars_file %}
{%- set stage_start = 'KUBELINE_STAGE_STARTING' %}
{%- set stage_success = 'KUBELINE_STAGE_FINISHED' %}
{%- set stage_failure = 'KUBELINE_STAGE_FAILURE' %}
{%- set init_string = '
function fail() {{
    echo "{0}" >> {1} 2>&1
}}
trap fail EXIT
until [ -f "{1}" ]; do
    sleep 1
done
if grep "{0}" {1}; then
    echo "exiting due to previous stage failure..."
    exit 0
fi
echo "starting"
'.strip() %}
{%- set exit_string = 'echo "{0}" >> {1} 2>&1\ntrap : 0' %}
apiVersion: batch/v1
kind: Job
metadata:
  generateName: "kl-{{ pipeline }}-"
  labels:
    app: kubeline
    type: job
    pipeline: "{{ pipeline }}"
    commit: "{{ commit }}"
    commit_short: "{{ short_commit }}"
spec:
  # run only one single pod of the job
  backoffLimit: 0
  completions: 1
  template:
    metadata:
      labels:
        app: kubeline
        type: job
        pipeline: "{{ pipeline }}"
        commit: "{{ commit }}"
        commit_short: "{{ short_commit }}"
    spec:
      activeDeadlineSeconds: 4000
      restartPolicy: Never
      containers:
      {%- set stage_id = '0-clone' %}
      {%- set log_file = '{}/{}'.format(log_dir, stage_id) %}
      - name: job-runner
        image: {{ job_runner_image }}
        imagePullPolicy: Always
        args:
        - "{{ pipeline }}"
        - --stages={% for stage in stages %}{{ loop.index }}-{{ stage.name }},{% endfor %}{{ stage_id }}
        - --log-dir={{ log_dir }}
        - --env-vars-file=kubeline-vars.sh
        - --start={{ stage_start }}
        - --success={{ stage_success }}
        - --failure={{ stage_failure }}
        - --influxdb-host={{ influxdb_host }}
        - --influxdb-db={{ influxdb_db }}
        - --time-limit=3600
        volumeMounts:
        - name: logs
          mountPath: {{ log_dir }}
      - name: {{ stage_id }}
        image: alpine/git
        workingDir: {{ work_dir }}
        command: [sh]
        args:
        - -ceux
        - |
          {{ init_string.format(stage_failure, log_file)|indent(10) }}
          mkdir -p -m 700 ~/.ssh
          cp /git-key/id_rsa ~/.ssh/
          chmod 700 ~/.ssh/id_rsa
          export GIT_SSH_COMMAND="ssh -o StrictHostKeyChecking=no"
          (
            git clone -q {{ config.git_url }} .
            git checkout -q {{ commit }}
          ) >> {{ log_file }} 2>&1
          {{ exit_string.format(stage_success, log_file)|indent(10) }}
        volumeMounts:
        - name: git-key
          mountPath: /git-key
        - name: work
          mountPath: {{ work_dir }}
        - name: logs
          mountPath: {{ log_dir }}
      {%- for stage in stages %}
        {%- set stage_id = '{}-{}'.format(loop.index, stage.name) %}
        {%- set log_file = '{}/{}'.format(log_dir, stage_id) %}
      - name: {{ stage_id | replace("_","-") }}
        {%- if stage.type == 'docker-build' or 'docker-push'%}
        image: alpine:3.9
        {%- elif stage.type == 'docker-compose' %}
        image: docker/compose:1.24.0
        {%- else %}
        image: {{ stage.image }}
        {%- endif %}
        workingDir: {{ work_dir }}
        command: [sh]
        args:
        - -ceux
        - |
          {{ init_string.format(stage_failure, log_file)|indent(10) }}
          source {{ env_vars_path }}
          (
          {%- if stage.type == 'docker-build' %}
            {%- set docker_image = 'kubeline-{}:{}'.format(stage.name, short_commit) %}
            docker build -t {{ docker_image }} -f {{ stage.dockerfile }} {{ stage.build_dir }}

          {%- elif stage.type == 'docker-push' %}
            {%- set docker_image = 'kubeline-{}:{}'.format(stage.from_stage, short_commit) %}
            {%- for tag in stage.tags %}
            docker tag {{ docker_image }} "{{ stage.repo }}:{{ tag }}"
            docker push "{{ stage.repo }}:{{ tag }}"
            docker rmi "{{ stage.repo }}:{{ tag }}"
            {%- endfor %}
            docker rmi {{ docker_image }}

          {%- elif stage.type == 'docker-compose' %}
            if ! docker-compose -f {{ stage.compose_file }} run --rm {{ stage.service_name }}; then
              docker-compose -f {{ stage.compose_file }} down
              false
            fi
            docker-compose -f {{ stage.compose_file }} down

          {%- else %}
            {%- set docker_image = '' %}
            {%- for cmd in stage.commands %}
            {{ cmd | indent(12) }}
            {%- endfor %}
          {%- endif %}
          ) >> {{ log_file }} 2>&1

          {{ exit_string.format(stage_success, log_file)|indent(10) }}
        env:
        - name: KUBELINE_GIT_BRANCH
          value: "{{ config.branch }}"
        - name: KUBELINE_GIT_COMMIT
          value: "{{ commit }}"
        - name: KUBELINE_GIT_COMMIT_SHORT
          value: "{{ short_commit }}"
        {%- if stage.type == 'docker-build' or 'docker-push' or 'docker-compose' %}
        - name: KUBELINE_DOCKER_IMAGE
          value: "{{ docker_image }}"
        {%- endif %}
        {%- if 'env_from_secret' in config %}
        envFrom:
        - secretRef:
            name: {{ config.env_from_secret }}
        {%- endif %}
        volumeMounts:
        - name: work
          mountPath: {{ work_dir }}
        - name: logs
          mountPath: {{ log_dir }}
        {%- if stage.type == 'docker-build' or 'docker-push' or 'docker-compose' %}
        - name: docker-socket
          mountPath: /var/run/docker.sock
        - name: docker-binary
          mountPath: /usr/bin/docker
          {%- if 'docker_secret' in config %}
        - name: docker-creds
          mountPath: /root/.docker/config.json
          subPath: .dockerconfigjson
          {%- endif %}
        {%- endif %}
      {%- endfor %}
      volumes:
      - name: work
        emptyDir:
          medium: Memory
      - name: logs
        emptyDir:
          medium: Memory
      - name: docker-socket
        hostPath:
          path: /var/run/docker.sock
      - name: docker-binary
        hostPath:
          path: /usr/bin/docker
      - name: git-key
        secret:
          secretName: {{ git_key_secret }}
      {%- if 'docker_secret' in config %}
      - name: docker-creds
        secret:
          secretName: {{ config.docker_secret }}
      {%- endif %}

